name: CI

on:
  push:
    branches: [master]
    paths:
      - "grammar.js"
      - "src/**"
      - "bindings/**"
      - "binding.gyp"
  pull_request:
    paths:
      - "grammar.js"
      - "src/**"
      - "bindings/**"
      - "binding.gyp"

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  test:
    name: Test parsers
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-14]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up tree-sitter
        uses: tree-sitter/setup-action/cli@v1
      - name: Clone examples
        uses: actions/checkout@v4
        with:
          path: examples/lemminx
          repository: eclipse/lemminx
          sparse-checkout: org.eclipse.lemminx/src/test/resources
          ref: 6b12cd0a89205c2791ef1240e0d8401103f8c9a9
      - name: Run tests
        uses: tree-sitter/parser-test-action@v2
        with:
          test-rust: true
          test-node: true
          test-python: true
          test-go: true
          test-swift: true
